### ISSUE TITLE
保存拖拽后的 task 位置

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/dida#116]
![dida-task3](https://user-images.githubusercontent.com/12064746/215426413-18007b1f-c16c-4fe2-bd04-3d413893afe1.gif)

## 期望

拖拽 task 位置后 可以保存起来 

实现方式就是需要加一个 index 来保存 task 的位置到 db
然后获取数据后 需要基于 index 来排个序

**Comment by Zuowendong** [comment]
> 你好，我的想法是在 indexedDB 的 projects 和 tags 的值中加一个 index 数组用来索引 task 的排序，但是我发现 SmartProjectNames 如 “已完成” ， “垃圾桶” 并没有在 indexedDB 中有存储，获取它们的 tasks 值是通过 state 过滤得到的，是否考虑将 SmartProjectNames 也用类似于 projects 和 tags 的方式存储起来呐

我觉得还是只在task上添加一个index来控制排序 这样的方案比较方便，我尝试实现了一下已提交了pr
1. 新增task时，基于之前是用unshift头插的方法，排序用的倒叙，那每次新增的task的index值应该是当前项目下原本tasks数组的长度
2. 上下拖拽时候需要更新改变位置的task的index，我没有采用拖拽后整个数组重新赋值，而是比较了新旧位置只更新这其中涉及位置更新的几个task
3. 移动到其他项目分组时，当前tasks 和 目标项目分组的tasks 都需要重新计算各taskd的index

**Comment by Zuowendong** [comment]
@cuixiaorui 额外有个问题， vuedraggable这个插件中拖拽事件的 e 是什么类型，也没找到它导出类型，只能用any怎么处理

**Comment by Debbl** [comment]
> 

https://github.com/SortableJS/Sortable#options 这个库好像用了这个库，类型好像是这个，但是这个组件本身好像就没有写定义这个类型

**Comment by cuixiaorui** [comment]
> 

我们可以在产品设计上规避这个问题
task在垃圾桶和完成 project 里面不运行拖拽
