### ISSUE TITLE
访问项目正式环境报错，无法加载页面

### ISSUE THREAD

**Issue by Nauxscript** [cuixueshe/dida#127]
控制台输出 `indexedDB` 报错：
```
Uncaught (in promise) ："Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found.
 NotFoundError: Failed to execute 'transaction' on 'IDBDatabase': One of the specified object stores was not found."
```

<img width="783" alt="image" src="https://user-images.githubusercontent.com/13010589/216757049-f076dd81-4f54-42cd-8c08-c56d72f5cb97.png">

**Comment by Debbl** [comment]
可以试一下清空浏览器 indexDB 的缓存

**Comment by Nauxscript** [comment]
> 可以试一下清空浏览器 indexDB 的缓存

确实可以，这是什么原因？数据字段发生了变化吗？

**Comment by Debbl** [comment]
> > 可以试一下清空浏览器 indexDB 的缓存
> 
> 确实可以，这是什么原因？数据字段发生了变化吗？

因为这个是 vite 项目默认的端口，有可能你的其他的 vite 项目也使用了 indexDB，有冲突吧，可能

**Comment by Nauxscript** [comment]
> > > 可以试一下清空浏览器 indexDB 的缓存
> > 
> > 
> > 确实可以，这是什么原因？数据字段发生了变化吗？
> 
> 因为这个是 vite 项目默认的端口，有可能你的其他的 vite 项目也使用了 indexDB，有冲突吧，可能

这样子，难道是因为这个项目我在本地开发使用的也是同个端口的原因？
