### ISSUE TITLE
无法创建清单

### ISSUE THREAD

**Issue by Nauxscript** [cuixueshe/dida#128]
![image](https://user-images.githubusercontent.com/13010589/216878483-bf1c2d8f-3cef-4c1e-8e8c-947cb21835cc.png)

原本已有对应的创建清单逻辑，但因为树的节点的 `suffix` 做了调整，所以需要把原来的触发创建清单弹框的逻辑调整到现在的 `suffix` 按钮事件上，可参考标签创建的逻辑和原来的创建清单核心逻辑 [pr](https://github.com/cuixueshe/dida/pull/62)

**Comment by Nauxscript** [comment]
@xianjianlf2 哥们，你有空调整不？

**Comment by xianjianlf2** [comment]
> @xianjianlf2 哥们，你有空调整不？

111  现在看
