### ISSUE TITLE
垃圾桶 task 右键中移动到和删除的功能有动画但没有实质效果

### ISSUE THREAD

**Issue by Puellaquae** [cuixueshe/dida#138]
在垃圾桶中的 task 右键选择移动到和删除会触发弹窗和条目消失的效果，但没发生任何数据上的实质变化。建议可以将菜单条目变灰禁用或剔除掉这些条目。

**Comment by Nauxscript** [comment]
在垃圾桶中应该是可以：
- 永久删除
- 恢复

滴答清单：
![image](https://user-images.githubusercontent.com/13010589/217162365-d780c446-079e-4d35-954e-23d4a8cc6bec.png)

**Comment by Nauxscript** [comment]
closed with this feature #139
