### ISSUE TITLE
保存拖拽后的 task 位置，有一点疑问？

### ISSUE THREAD

**Issue by Debbl** [cuixueshe/dida#140]
你好，我看了这个 issue https://github.com/cuixueshe/dida/issues/116 ， 有一个 pr https://github.com/cuixueshe/dida/pull/126 解决了这个问题。但是我发现如果一个 task 在一个 `清单` 中又在一个 `标签` 中的时候，调整 task 的位置可能会导致该 task 在其他的 `清单` 或 `标签` 中的位置错乱。

- 如 初始 的时候 `写代码` 的 `index` 为 0 在 `生活` 和 `标签1` 中的位置如下

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/61053131/217170804-550d0f93-7554-4291-8278-a0e4643a4b5c.png">
<img width="1182" alt="image" src="https://user-images.githubusercontent.com/61053131/217170897-44c4e7e2-56fd-4b32-80fa-c523dfcb8776.png">

- 当我在 `生活` 中将 `index` 变为 2 时， `写代码` 在 `生活` 和 `标签1` 中的位置如下

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/61053131/217171251-6a1f9d16-7823-40be-bc88-b1771a0ff9d2.png">
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/61053131/217171307-28c73bc6-68dd-4644-9234-b43fd17781e5.png">

我看客户端 滴答清单 的行为好像不是这样，你看有必要解决一下这个问题吗？

**Comment by Nauxscript** [comment]
是这样子的，滴答是支持标签内的任务排序和清单内的任务排序分开的，具体的实现方式是：
1. 清单内任务排序是用序号的方式实现排序，即每个任务有一个序号字段记录当前任务顺序；
2. 其他如标签内的任务排序，看滴答的接口返回是有另外一个保存的

所以感觉这个如果要详细实现起来也挺复杂的

**Comment by Debbl** [comment]
https://github.com/cuixueshe/dida/issues/116#issuecomment-1411510458
是的，我之前有一个想法就是每一个 `projects` 和 `tags` 单独保存自己 `tasks` 索引，你看一下这样是否可行。

**Comment by cuixiaorui** [comment]
现在解决这个问题了
在数据库里面保存了当前 task 的位置信息 position 字段
显示在其他 list 的时候， 比如完成list 基于编辑时间来排序
