### ISSUE TITLE
清单名称可以重复

### ISSUE THREAD

**Issue by Debbl** [cuixueshe/dida#143]
是否需要限制一下避免清单名称重复

<img width="1014" alt="image" src="https://user-images.githubusercontent.com/61053131/217198880-faffc898-aa28-4887-81b3-e2e8d562c1c6.png">

<img width="480" alt="image" src="https://user-images.githubusercontent.com/61053131/217199078-40966c0f-fa1c-41b0-8950-473fce2e8d9c.png">

**Comment by Nauxscript** [comment]
我觉得可以限制一下

**Comment by xianjianlf2** [comment]
fixed: #145
