### ISSUE TITLE
commandModal的测试还能更严谨些

### ISSUE THREAD

**Issue by jgqandsh** [cuixueshe/dida#156]
问题描述:
 文件路径: `apps/teach-frontend/src/components/command/tests/commandModal.spec.ts`
1. commandModal的测试文件中，`beforeEach`调用了`closeCommandModal`使得每个用例都有一个初始值。
```
beforeEach(() => {
    const { closeCommandModal } = useCommandModal()
    closeCommandModal()
 })
```
然而第二个测试用例就是用来测试`closeCommandModal`的。
换句话说，在不知道`closeCommandModal`是否正确的情况下，在`beforeEach`中就调用了它。
如果`openCommandModal`没有问题，但是`closeCommandModal`有问题的话，测试也不会通过。
`openCommandModal`和`closeCommandModal`的测试用例都是最终判断`expect(showCommandModal.value).toBe(..)`,
根据小步走的原则，将`beforeEach`改成下面的形式，会不会更严谨一些:
```
beforeEach(() => {
  const { showCommandModal } = useCommandModal()
  showCommandModal.value = false 
})
```
2. 测试`closeCommandModal`时, `beforeEach`中已经调用了`closeCommandModal`,在测试用例中再调用一次`closeCommandModal`, 会不会影响测试结果呢？
如果先打开，然后再关闭，这样测试会不会更有效果呢？
````
it('should be close command modal', () => {
  const { openCommandModal, closeCommandModal, showCommandModal } = useCommandModal()
  //先打开
  openCommandModal()
  closeCommandModal()
   expect(showCommandModal.value).toBe(false)
})
```
以上两点谈不上问题，不知道这样修改了会不会更严谨一些呢。

**Comment by cuixiaorui** [comment]
问题一：
对于前置方法 都需要假定它是没有问题的
这里的 `closeCommandModal` 就是前置方法
不然在写其他 test case 的时候就没法写了  
因为基于前门准备数据必须要调用除了需要测试接口之外的接口
举个例子 在测试 `removeTodo` 的时候 就需要先调用 `addTodo`  
如果你不假设 `addTodo` 是正确的话 那么 `removeTodo` 也就没法测

对于是调用 `closeCommandModal` 还是直接赋值 `showCommandModal.value = false`
在这个 case 中区别不大  看自己的喜好 

问题二：
这里主要是为了和测试 `openCommandModal` 对齐
调用一个接口 然后验证其输出
从可读性上来讲 没啥问题

如果是要提前加 `openCommandModal` 的话 ，也挺好， 不过在测试 `openCommandModal` 的时候，也需要调用下 `closeCommandModal ` 使其对齐

```js
  it('should be open command modal', () => {
    const { openCommandModal, showCommandModal, closeCommandModal } = useCommandModal()
    closeCommandModal()

    openCommandModal()

    expect(showCommandModal.value).toBe(true)
  })
```
至于为什么在 beforeEach 里面都调用了 `closeCommandModal`  了 现在为什么还需要调用一次
是因为职责不一样， beforeEach 是为了 reset data ， 而这里是明确一个前置动作
