### ISSUE TITLE
创建 tag

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/dida#43]
![dida-task2](https://user-images.githubusercontent.com/12064746/211275515-1dc6a972-d2dc-4287-9bf1-d9b9d058e60b.gif)

## Tasking
- [ ] 鼠标 hover 在便签上的时候 显示 + 
- [ ]  点击 + 按钮之后显示创建 tag 的 panel
- [ ] 点击关闭按钮或者点击右上角的关闭按钮可以关闭 panel
- [ ] 点击保存按钮后 可以新创建一个 tag
- [ ] 用户可以在便签栏看到新创建的 tag

**Comment by Nauxscript** [comment]
这个 issue @hildxd 和我沟通过，我来接手试试看，如有变动会在这边反馈
