### ISSUE TITLE
删除 tag

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/dida#46]
![dida-task4](https://user-images.githubusercontent.com/12064746/211277199-1379c1f1-cbd9-4386-b696-69dcbbc5a839.gif)

## Tasking
- [ ] 用户点击删除按钮的时候 显示删除提示框
- [ ] 用户点击取消按钮的时候 可以取消删除提示框
- [ ] 用户点击确认按钮的时候 tag 会被删除掉

**Comment by Nauxscript** [comment]
1

**Comment by Nauxscript** [comment]
这个任务依赖于 #43 ，等那个好了我动手做
