### ISSUE TITLE
给项目起个好名字 | 征集好名字

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/dida#76]
现在的项目名字太 low 了 同学们有没有好的意见和建议？ 

说明一下为什么要叫推荐的名字 

后面我们投票来决定 看看谁的寓意更好

**Comment by Nauxscript** [comment]
"WeMadeIt", 这个项目是代办事项类的工具，我们使用这类工具就是为了能完成我们建立的代办，we made it，蕴含着已经完成建立的目标（或者想要完成目标的愿景）；同时，这个项目也是我们大家一起做的（we made it）。

**Comment by likui628** [comment]
### vida

**Comment by alexzhang1030** [comment]
reminder

**Comment by zhengbangbo** [comment]
Later

**Comment by enochzzz** [comment]
Cocher

法语

vt.
刻痕， 作记号， 加标记， 打勾， 打叉

[Cocher 释义](https://www.frdic.com/dicts/fr/cocher)

这我不是mvp？：）

**Comment by Hazel-Lin** [comment]
rappeler

**Comment by eynus** [comment]
wekker

**Comment by Psilocine** [comment]
diva

**Comment by susanliy** [comment]
ToDo

**Comment by leewei0923** [comment]
ToDone，涂单（划单）

**Comment by jersonwei** [comment]
Tatakai

**Comment by jersonwei** [comment]
Tatakai

**Comment by xianjianlf2** [comment]
Coupling
---
> 耦合效应（Coupling Induction），也称互动效应，联动效应在群体心理学中，人们把群体中两个或以上的个体通过相互作用而彼此影响从而联合起来产生增力的现象，称之为耦合效应。
