### ISSUE TITLE
feat: backend MVP

### ISSUE THREAD

**Issue by alexzhang1030** [cuixueshe/dida#80]
记录项目初始化 backend 进度：

- [x] Monorepo 初始化 - 使用 pnpm workspace, 分为 apps + packages 两个文件夹，apps 放 frontend 和 backend 源码，packages 放工具包（utils/deploy) 等 #103 
- [x] Nestjs 初始化配置 #146 
- [ ] 前后端类型共享构想（方案：公用类型配置或者使用 swagger，由后端生成 Dto 类型供前端使用）并初始化类型共享方案
- [ ] DB 初始化
- [ ] 数据表制定 + 初始化数据库迁移文件
- [ ] Todo API 开发
- [ ] 部署后端 Docker 配置

还有其他欢迎补充

**Comment by alexzhang1030** [comment]
@cuixiaorui 用 Monorepo 吗？如果确认的话，我应该会在周末开始

**Comment by cuixiaorui** [comment]
可以 开搞

**Comment by Seanxyc** [comment]
> 

关于类型共享，可以考虑下trpc

**Comment by cuixiaorui** [comment]
已完成
