### ISSUE TITLE
来来来 进来做个阶段性的盘点 & 头脑风暴一下

### ISSUE THREAD

**Issue by cuixiaorui** [cuixueshe/dida#87]
## 目前正在开发ing
- tag 模块
- 搜索模块
- 智能列表模块

这3个模块都可以不依赖后端 直接在前端模拟数据就可以完成
目前大家完成任务的效率非常的高 
不过已经出现有意思的问题了
某个 pr merged 后 会破坏之前的功能
当然因为现在对核心业务逻辑有测试覆盖 所以出现问题的大多是 UI 逻辑
这就需要组件测试和 e2e 来解决了

所以接下来我们的任务是要巩固好这三大模块的功能
不管是技术层面 还是从产品交互层面  都需要更上一层楼
同学们可以点吧点吧 测试一下 然后把发现的 bug 提到 issues 里面

## 下一步
下一步就是搭建好后端，然后引入用户的概念 包括常见的功能  注册 登录之类的

## 注意
- services 层的代码我在一直重构， 会基于单元测试来重新驱动实现等等。这是一个非常容易造成代码冲突的点 同学们可以先不提相关 pr 

## 头脑风暴
同学们目前对该项目有什么想法 或者有什么期待 在或者有什么意见和建议 留言我们讨论讨论  做个头脑风暴

**Comment by Nauxscript** [comment]
感觉可以根据当前开发进度建立 discussion 分区，有利于当前在做对应模块的人以及后续的要接手的人了解功能的设想、走向等，也方便大家一起沟通细化模块；比如我现在在做 tag 模块，我可以建立一个 tag 模块的讨论，大概描述我目前的思路，如果是其他人有更好的建议，可以提出，我可以参考，防止一个功能从开始就走歪。

**Comment by Draculabo** [comment]
可以拉个文档，统计目前模块分工、项目进度之类的

**Comment by alexzhang1030** [comment]
> 感觉可以根据当前开发进度建立 discussion 分区，有利于当前在做对应模块的人以及后续的要接手的人了解功能的设想、走向等，也方便大家一起沟通细化模块；比如我现在在做 tag 模块，我可以建立一个 tag 模块的讨论，大概描述我目前的思路，如果是其他人有更好的建议，可以提出，我可以参考，防止一个功能从开始就走歪。

discord 可以满足你的需求

**Comment by Nauxscript** [comment]
GitHub 不是有discussion 吗，感觉更适合一些；因为我们的参与者是随时可以参与进来的，而不是有固定的维护小组，如果是核心的参与者可以用discord，当然拉个 微信群可能来的更快一些

**Comment by jobn123** [comment]
可以用vim完成基本的操作
